### ISSUE TITLE
[Bug]: Label inverted

### ISSUE THREAD

**Issue by antonin-beev** [tremorlabs/tremor-blocks-issue-tracker#1]
### URL

https://blocks.tremor.so/blocks/logins#login-2

### Block name

Login

### Bug description

The email label is inverted with the password label

### What is expected?

```diff
-Password
+Email
-Email
+Password
```

### Screenshots

![image](https://github.com/tremorlabs/tremor-blocks-issue-tracker/assets/138325934/0efc9bdc-2ea7-4e68-9e7e-02c6f1cdd888)

### What browser(s) are you seeing the problem on?

Chrome, Brave

### What device(s) are you seeing the problem on? (if applicable)

Desktop

**Comment by christopherkindl** [comment]
Thanks for this, has been solved some time ago!
