### ISSUE TITLE
[Bug]: None of the badge blocks are working for me

### ISSUE THREAD

**Issue by janmohn** [tremorlabs/tremor-blocks-issue-tracker#12]
### URL

https://blocks.tremor.so/blocks/badges

### Block name

Badge 5, 6, 7

### Bug description

it seems like the classes with the word "tremor" in them aren't included in my project, despite all other blocks working; this is the first time I have seen CSS classes on components use the word tremor instead of generic tailwind classes.

e.g. from Badge Block 5

`<span className="inline-flex items-center space-x-1.5 rounded-tremor-full bg-tremor-background px-2.5 py-1 ring-1 ring-inset ring-tremor-ring dark:bg-dark-tremor-background dark:ring-dark-tremor-ring">
          <span className="text-tremor-label font-medium text-tremor-content dark:text-dark-tremor-content">
            In progress
          </span>`

### What is expected?

the css should work

### What is actually happening?

css not found in project

**Comment by severinlandolt** [comment]
Hi @janmohn, the badges you sent are for users of the NPM package (there we use our [own tremor tokens)](https://npm.tremor.so/docs/getting-started/theming). 

If you would like to use plain Tailwind CSS, switch to "Tremor" here: 
![CleanShot 2024-10-22 at 08 35 33@2x](https://github.com/user-attachments/assets/401b7280-e9c7-436d-98d5-56797f6be107)

**Comment by janmohn** [comment]
Hi, this means there is an error with your website because even though I'm on the copy and paste tab, it's still showing me the incorrect tremor, CSS classes as the copy and paste block

**Comment by severinlandolt** [comment]
Does this switch work correctly for you?
https://github.com/user-attachments/assets/837af7bc-ff4c-4415-9c89-5a9d0f41a7f5

Try to logout, clear the cookies for the site and login again

**Comment by janmohn** [comment]
Working now for me, thank you!
