### ISSUE TITLE
[Bug]: Text color of Upgrade CTA stays same on light and dark mode. 

### ISSUE THREAD

**Issue by faaiz99** [tremorlabs/tremor-blocks-issue-tracker#3]
### URL

https://blocks.tremor.so/blocks/pricing-sections

### Block name

Pricing Section 1

### Bug description

Text color of Upgrade CTA stays same on light and dark mode. 

### What is expected?

Text color of Upgrade CTA on dark mode should be white.

### What is actually happening?

Text color of Upgrade CTA on dark mode should be white instead of dark blue

### Screenshots

![pricing-incorrect-behavior](https://github.com/tremorlabs/tremor-blocks-issue-tracker/assets/44613754/dcb467b2-b4a5-4ff7-ac4c-a973490817ac)
![pricing-correct-behavior](https://github.com/tremorlabs/tremor-blocks-issue-tracker/assets/44613754/0d9ffdc6-3435-4afc-b529-4d72bdd4a3e8)

### What browser(s) are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on? (if applicable)

Desktop

**Comment by christopherkindl** [comment]
Hi @faaiz99, thanks for reaching out! This is actually by design. `text-dark-tremor-brand-inverted (blue-950)` is our preferred dark color for `text-tremor-brand-inverted`.

If you want to keep it white, simply do `dark:text-tremor-brand-inverted`
