### ISSUE TITLE
[Bug]: File Upload 8 is a dropdown

### ISSUE THREAD

**Issue by zknicker** [tremorlabs/tremor-blocks-issue-tracker#4]
### URL

https://blocks.tremor.so/blocks/file-upload#file-upload-8

### Block name

File Upload 8

### Bug description

The rendered preview for File Upload 8 is a dropdown menu.

![Screenshot 2024-04-27 at 12 11 53 AM](https://github.com/tremorlabs/tremor-blocks-issue-tracker/assets/1164085/1e0a4135-d409-4a10-920b-e125e2490f91)

### What is expected?

A file upload :).

### Any additional comments?

So excited to enjoy Blocks, thanks for the great product!

**Comment by christopherkindl** [comment]
Thanks, fixed! This should have been placed somewhere else! :)
