### ISSUE TITLE
[Bug]: Colors Property not working as expected in Donut chart 

### ISSUE THREAD

**Issue by sivaranjani07** [tremorlabs/tremor-blocks-issue-tracker#6]
### URL

https://blocks.tremor.so/blocks/donut-charts

### Block name

Colors in Donut chart

### Bug description

In our project we are using Donut chart .However, the Colors property is not working. Despite specifying the colors, the chart is displaying in black color. 

### What is expected?

Specified Colors needs to be displayed on the chart.

### What browser(s) are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on? (if applicable)

Desktop

**Comment by Lokesh-10Ki** [comment]
okay, where are the screenshots and code snippets.

**Comment by christopherkindl** [comment]
Hi @sivaranjani07,

what framework are you using (Next.js, ...)? Make sure that you define the import paths in the tailwind.config.ts correctly. 

E.g. for Next.js

```
  content: [
    './src/**/*.{js,ts,jsx,tsx}',

    // Path to Tremor module
    './node_modules/@tremor/**/*.{js,ts,jsx,tsx}',
  ],
```

Learn more [here](https://www.tremor.so/docs/getting-started/installation)
