### ISSUE TITLE
[Maybe a Bug]: Dark Theme Bar List 3

### ISSUE THREAD

**Issue by fl0wo** [tremorlabs/tremor-blocks-issue-tracker#9]
### URL

https://blocks.tremor.so/blocks/bar-lists#bar-list-3

### Block name

Bar List 3

### Bug description

Hi, is the white shadow below expected on dark theme?

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/1a6b49dc-c6ef-48fb-a4a1-b3d875b2a570">

### What is expected?

Not a negative effect on the shadow below the button:

<img width="1250" alt="image" src="https://github.com/user-attachments/assets/1a6b49dc-c6ef-48fb-a4a1-b3d875b2a570">

### What browser(s) are you seeing the problem on?

Chrome

### What device(s) are you seeing the problem on? (if applicable)

Desktop

### Any additional comments?

If it's expected to look like this, please close the issue as not an issue.

**Comment by fl0wo** [comment]
Instead we could have a block button (that takes all the width) and we can negate the color of the button to white (with black bg) 

I'm not a designer tho, just wondering

**Comment by christopherkindl** [comment]
Thx – That was a bug, should be solved now!
